parameters:
    fcm.client.class: Fresh\FirebaseCloudMessaging\Client

services:
    fcm.client:
        class: "%fcm.client.class%"
        arguments:
            - "%fcm.sender_id%"
            - "%fcm.server_key%"
            - "%fcm.endpoint%"
