parameters:
    firebase_cloud_messaging.client.class: Fresh\FirebaseCloudMessaging\Client
    firebase_cloud_messaging.symfony_dispatcher.class: Fresh\FirebaseCloudMessagingBundle\Service\SymfonyEventDispatcher

services:
    firebase_cloud_messaging.symfony_dispatcher:
        class: "%firebase_cloud_messaging.symfony_dispatcher.class%"
        public: false
        arguments:
            - "@event_dispatcher"

    firebase_cloud_messaging.client:
        class: "%firebase_cloud_messaging.client.class%"
        arguments:
            - "%firebase_cloud_messaging.sender_id%"
            - "%firebase_cloud_messaging.server_key%"
            - "%firebase_cloud_messaging.endpoint%"
            - "%firebase_cloud_messaging.guzzle_timeout%"
        calls:
            - [setEventDispatcher, ["@firebase_cloud_messaging.symfony_dispatcher"]]
