services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
#            $senderId: '%firebase_cloud_messaging.sender_id%'
            $serverKey: '%firebase_cloud_messaging.server_key%'
            $endpoint: '%firebase_cloud_messaging.endpoint%'
            $guzzleTimeOut: '%firebase_cloud_messaging.guzzle_timeout%'

    Fresh\FirebaseCloudMessagingBundle\Client\FirebaseClient:
        class: Fresh\FirebaseCloudMessagingBundle\Client\FirebaseClient

    Fresh\FirebaseCloudMessagingBundle\Client\HttpClient:
        class: Fresh\FirebaseCloudMessagingBundle\Client\HttpClient

    Fresh\FirebaseCloudMessagingBundle\Response\ResponseProcessor:
        class: Fresh\FirebaseCloudMessagingBundle\Response\ResponseProcessor

    Fresh\FirebaseCloudMessagingBundle\Message\Builder\MessageBuilder:
        class: Fresh\FirebaseCloudMessagingBundle\Message\Builder\MessageBuilder

    Fresh\FirebaseCloudMessagingBundle\Command\:
        resource: '../../Command/'
